author: cedeel
database: false
description: Find when a player last left the server.
main: com.cedeel.timetracker.Plugin
name: ${name}
website: ${url}
version: ${version}
commands:
  seen: 
    description: Find when a player was last online on your server
    usage: /seen username
    permission: timetracker.seen
  playtime: 
    description: See when your first login was
    usage: /playtime
    permission: timetracker.playtime
permissions:
  timetracker.playtime:
    description: See your play time.
    default: true
  timetracker.seen:
    description: See first, last and total play time.
    default: op

    
